In [25]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [26]:
env = gym.make('FrozenLake-v1')

In [27]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [28]:
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [43]:
rewards_all_episodes = []

#Q learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #Exploration and Explotation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Updating the Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
            
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
    
    
#Calculate the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print('********** Average reward per thousand episodes **********\n')
for r in rewards_per_thousand_episodes:
    print(count, ': ', str(sum(r/1000)))
    count += 1000
    
    
#Print updated Q-table
print('\n\n********** Q-table **********\n')
print(q_table)

********** Average reward per thousand episodes **********

1000 :  0.035000000000000024
2000 :  0.19400000000000014
3000 :  0.4040000000000003
4000 :  0.5630000000000004
5000 :  0.6600000000000005
6000 :  0.6940000000000005
7000 :  0.6760000000000005
8000 :  0.7130000000000005
9000 :  0.6600000000000005
10000 :  0.6790000000000005


********** Q-table **********

[[0.53506593 0.52474264 0.51771758 0.50474396]
 [0.30537829 0.33907512 0.34588209 0.51284434]
 [0.41968686 0.40544045 0.40800954 0.49297923]
 [0.33507856 0.26951793 0.2775666  0.47534485]
 [0.54486647 0.44050993 0.42121781 0.41230142]
 [0.         0.         0.         0.        ]
 [0.18105004 0.1694083  0.23865825 0.1475937 ]
 [0.         0.         0.         0.        ]
 [0.36935623 0.37848814 0.41355051 0.5650547 ]
 [0.41969807 0.5717716  0.31338047 0.38956645]
 [0.51794416 0.44390038 0.24225868 0.40681144]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.39139606 0.4373413

In [44]:
for episodes in range(3):
    state = env.reset()
    done = False
    print('**********Episodes  ', episode + 1, '**********\n')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                print('**** You reached the goal! ****')
            else:
                print('**** You fellthrough a hole! ****')
                time.sleep(3)
                
            clear_output(wait = True)
            break
            
        state = new_state
        
env.close
                

<bound method Wrapper.close of <TimeLimit<OrderEnforcing<FrozenLakeEnv<FrozenLake-v1>>>>>